name: Test

on: push

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                      ${{ runner.os }}-maven-
            - run: |
                  java -version
                  echo $JAVA_HOME
            - run: ./mvnw install
            - uses: codecov/codecov-action@v1
#            - run: ./mvnw test
            - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
            - run: chmod +x codecov
            - run: ./codecov

